default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: mysql2
  username: root

development:
  <<: *default
  database: personalitytest_development
  password:
  host: localhost

test:
  <<: *default
  database: personalitytest_test
  password:
  host: localhost

production:
  <<: *default
  database: personalitytest_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock