class CreateTests < ActiveRecord::Migration[6.0]
  def change
    create_table :tests do |t|
      t.integer :item1,        null: false
      t.integer :item2,        null: false
      t.integer :item3,        null: false
      t.integer :item4,        null: false
      t.integer :item5,        null: false
      t.integer :item6,        null: false
      t.integer :item7,        null: false
      t.integer :item8,        null: false
      t.integer :item9,        null: false
      t.integer :item10,       null: false
      t.integer :item11,       null: false
      t.integer :item12,       null: false
      t.integer :item13,       null: false
      t.integer :item14,       null: false
      t.integer :item15,       null: false
      t.integer :item16,       null: false
      t.integer :item17,       null: false
      t.integer :item18,       null: false
      t.integer :item19,       null: false
      t.integer :item20,       null: false
      t.integer :item21,       null: false
      t.integer :item22,       null: false
      t.integer :item23,       null: false
      t.integer :item24,       null: false
      t.integer :item25,       null: false
      t.integer :item26,       null: false
      t.integer :item27,       null: false
      t.integer :item28,       null: false
      t.integer :item29,       null: false
      t.integer :item30,       null: false
      t.integer :item31,       null: false
      t.integer :item32,       null: false
      t.integer :item33,       null: false
      t.integer :item34,       null: false
      t.integer :item35,       null: false
      t.integer :item36,       null: false
      t.integer :item37,       null: false
      t.integer :item38,       null: false
      t.integer :item39,       null: false
      t.integer :item40,       null: false
      t.integer :item41,       null: false
      t.integer :item42,       null: false
      t.integer :item43,       null: false
      t.integer :item44,       null: false
      t.integer :item45,       null: false
      t.integer :item46,       null: false
      t.integer :item47,       null: false
      t.integer :item48,       null: false
      t.integer :item49,       null: false
      t.integer :item50,       null: false
      t.integer :item51,       null: false
      t.integer :item52,       null: false
      t.integer :item53,       null: false
      t.integer :item54,       null: false
      t.integer :item55,       null: false
      t.integer :item56,       null: false
      t.integer :r_score,      null: false
      t.integer :y_score,      null: false
      t.integer :b_score,      null: false
      t.integer :g_score,      null: false
      t.integer :color_id,     null: false
      t.timestamps
    end
  end
end
